### ISSUE TITLE
Feature: Query and paste from the clipboard

### ISSUE THREAD

**Issue by nathanmsmith** [ojroques/nvim-osc52#13]
While most terminal emulates don't support reading from the clipboard, there is growing support for this feature – the next release of iTerm (3.5) will allow for [querying the clipboard](https://iterm2.com/documentation-escape-codes.html).

It'd be nice to support pasting for those who use a terminal emulator that supports querying the clipboard via OSC 52!

**Comment by ojroques** [comment]
I will definitely look into it :) I don't have time this week and the next but after I should be able to work on this.

**Comment by ojroques** [comment]
I added a paste method. I have no way of testing it, I'm not even sure how it would work in practice but it's there :) I guess we'll know more when iTerm 3.5 will be out.

**Comment by ikalnytskyi** [comment]
Hey @ojroques, thanks for working on this! I don't want to bring bad news but it's unlikely going to work. The Foot terminal on Linux supports OSC-52 for copying/pasting. I tried this patch and it didn't work for me. It actually makes sense because according to OSC-52, the terminal returns `base64`-encoded clipboard content surrounded by OSC-52 escape codes, and it's up to the caller to unescape and decode the data.

You can check how it's supposed to work in this script there → https://github.com/rumpelsepp/oscclip/blob/master/oscclip/__init__.py. I tried the script and it worked well for me.

Now I wonder, is this even possible to work with `/dev/tty` from Lua API? Can the file descriptor for that device be changed to be non-blocking? :thinking:

**Comment by ojroques** [comment]
Thanks for the info! I'll check how it can be implemented in the plugin when I have time. Probably not anytime soon though.

**Comment by rnhmjoj** [comment]
Sadly, I'm fairly certain that pasting can't be implemented as a simple plugin.
Standard Lua has no facilities for non-blocking file I/O and changing the terminal mode, so this would require binding to a C library or patching neovim for these parts.

**Comment by ikalnytskyi** [comment]
JFYI, native OSC-52 support has been landed to NeoVim master branch. :partying_face: It goes w/o saying that it includes both copying and pasting.

https://github.com/neovim/neovim/pull/25872

**Comment by ojroques** [comment]
That's great news! I updated the README with a disclaimer.
